### ISSUE TITLE
Getting "Error: socket hang up" when doing serverless deploy

### ISSUE THREAD

**Issue by cwilkes** [serverless/serverless-google-cloudfunctions#54] opened 2017-03-26 06:27 UTC
Not much to go on here.  Tried to look in stackdriver for more info, didn't find anything obvious.

  Error --------------------------------------------------

     Error: socket hang up

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Error: socket hang up
    at filArgs.reduce (/Users/cwilkes/Documents/workspace/hackathon/cjw_gf1/node_modules/serverless-google-cloudfunctions/provider/googleProvider.js:65:33)
    at JWT.OAuth2Client._postRequest (/Users/cwilkes/Documents/workspace/hackathon/cjw_gf1/node_modules/google-auth-library/lib/auth/oauth2client.js:402:3)
    at postRequestCb (/Users/cwilkes/Documents/workspace/hackathon/cjw_gf1/node_modules/google-auth-library/lib/auth/oauth2client.js:362:12)
    at Request._callback (/Users/cwilkes/Documents/workspace/hackathon/cjw_gf1/node_modules/google-auth-library/lib/transporters.js:70:30)
    at self.callback (/Users/cwilkes/Documents/workspace/hackathon/cjw_gf1/node_modules/request/request.js:188:22)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/Users/cwilkes/Documents/workspace/hackathon/cjw_gf1/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketOnEnd (_http_client.js:394:9)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
From previous event:
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:156:22)
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:95:31)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:23:50)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by jpoutrin** [comment] 2017-04-27 13:57
Same issue.
Same code was working before.
the google api might have changed or the serverless api as there is some deprecation Warnings using the latest version

**Comment by pmuens** [comment] 2017-04-27 15:52
Thanks for the update @jpoutrin 👍 

🤔 could really be a problem with the APIs we use...

**Comment by pmuens** [comment] 2017-05-18 11:38
Thanks again for reporting! Tried to reproduce it but unfortunately was not able to do so.

My assumption is that it's due to some problems on Googles end (GCF is still in `beta`). I'll close this one for now. Feel free to comment / reopen if you see this issue popping up again... 👍

**Closed by pmuens** 2017-05-18 11:38 UTC
Labels: bug

**Comment by steindaniel** [comment] 2017-12-15 11:38
@cwilkes Serverless relies on read/write access to Google Cloud Storage to upload artefacts. I had to add the following permissions to my service account to solve the problem
```
storage.buckets.create
storage.buckets.delete
storage.buckets.get
storage.buckets.list
storage.buckets.update
storage.objects.create
storage.objects.delete
storage.objects.get
storage.objects.list
storage.objects.update
```

@pmuens Am I right that Serverless doesn't currently check for storage permissions?

**Comment by pmuens** [comment] 2018-03-13 18:23
> @pmuens Am I right that Serverless doesn't currently check for storage permissions?

Yes, that's correct :+1:
